# Generated by Django 5.0.6 on 2024-08-31 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0006_alter_attendeeprofile_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendee",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="slug",
        ),
    ]
