# Generated by Django 5.0.6 on 2024-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0009_remove_createview_seo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createview",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="faction",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
