# Generated by Django 5.0.6 on 2024-12-07 19:23

import address.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("faction", "0010_alter_createview_slug_alter_faction_slug"),
        ("organization", "0005_alter_organization_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeprofile",
            options={
                "verbose_name": "Attendee Profile",
                "verbose_name_plural": "Attendee Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderprofile",
            options={
                "verbose_name": "Leader Profile",
                "verbose_name_plural": "Leader Profiles",
            },
        ),
        migrations.AddField(
            model_name="attendee",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="leader",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="attendeeprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profiles",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profiles",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaderprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profiles",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="leaderprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profiles",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="leaderprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
