# Generated by Django 5.0.6 on 2024-12-10 22:34

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0011_alter_attendeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="attendee",
            managers=[
                ("attendees", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="attendee",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="slug",
        ),
    ]
