# Generated by Django 5.0.6 on 2024-12-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0013_alter_attendeeprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="leaderprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
