# Generated by Django 5.2.8 on 2025-11-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0014_attendeeprofile_slug_leaderprofile_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leader",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="faction",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="last_activity_by",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="user_ptr",
        ),
        migrations.DeleteModel(
            name="Attendee",
        ),
        migrations.DeleteModel(
            name="Leader",
        ),
    ]
