# Generated by Django 5.2.8 on 2025-11-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0015_remove_leader_created_by_remove_leader_faction_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DROP TABLE IF EXISTS faction_attendee;
DROP TABLE IF EXISTS faction_leader;
""",
            reverse_sql="-- no-op reverse",
        ),
    ]
