# Generated by Django 5.2.8 on 2025-11-19 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("faction", "0016_delete_attendee_leader"),
        ("organization", "0007_organization_unique_org_slug_per_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="leaderprofile",
            options={},
        ),
        migrations.AddConstraint(
            model_name="attendeeprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_attendee_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="faction",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_faction_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_leader_slug_per_org"
            ),
        ),
    ]
