# Generated by Django 5.2.8 on 2025-11-19 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("faction", "0018_faction_address"),
        ("organization", "0008_organization_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeprofile",
            options={
                "verbose_name": "Attendee Profile",
                "verbose_name_plural": "Attendee Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderprofile",
            options={
                "verbose_name": "Leader Profile",
                "verbose_name_plural": "Leader Profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="attendeeprofile",
            constraint=models.UniqueConstraint(
                fields=("faction", "user"), name="unique_attendee_per_faction_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderprofile",
            constraint=models.UniqueConstraint(
                fields=("faction", "user"), name="unique_leader_per_faction_user"
            ),
        ),
    ]
