# Generated by Codex on 2026-04-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0020_leaderprofile_is_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeprofile",
            options={
                "verbose_name": "Attendee",
                "verbose_name_plural": "Attendees",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderprofile",
            options={
                "verbose_name": "Leader",
                "verbose_name_plural": "Leaders",
            },
        ),
    ]
